# Generated by Django 3.0.6 on 2020-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
