# Generated by Django 3.0.6 on 2020-08-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Mero Order', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='serviceOne',
            field=models.CharField(default='Mero Order', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='serviceThree',
            field=models.CharField(default='Mero', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='serviceTwo',
            field=models.CharField(default='Mero', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(default='Mero'),
            preserve_default=False,
        ),
    ]
